config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pages/newproject' => 'pages#newproject'
  get 'pages/kwendoo' => 'pages#kwendoo'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def newproject
  end
   def kwendoo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= csrf_meta_tags %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
	<div class="jumbo">
		<div class="filter-black flex-container">
			<div class="flex-item text-center">
				<h1>DES SOLUTIONS POUR <br> UNE AFRIQUE EMERGEANTE.</h1>
				<%= link_to 'Découvrez les projets', root_path, class: 'btn-medium-yellow' %>
				<%= link_to 'Proposez un projet', root_path, class: 'btn-medium-red'%>
			</div>
		</div>
	</div>

	<div class="discover text-center">
		<div class="discover-title">
			Decouvrez des projets innovants ambitieux et solides
		</div>
		<div class="discover-title-project">
			Les projets coup de coeur
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<div class="project-card">
						<div class="img-1">
						</div>
						<div class="description">
							DÉVELOPPER LE COLLÈGE SAINT-JEAN BAPTISTE DE BANGOU.
						</div>
						<div class="location">
							<div class="icon">
								<%= image_tag "placeholder.svg" %>
							</div>
							<div class="location-text">
								Bangou, OUEST
							</div>
						</div>
						<div class="price-day">
							<div class="price">
								€120 (6%)
							</div>
							<div class="day">
								16 jours restants
							</div>
						</div>						
						<div class="statement">	
							<progress id="avancement" value="30" max="100"></progress>
						</div>
						<%= link_to 'Voir le projet', root_path, class:'btn-medium-yellow-w-m btn-block' %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="project-card">
						<div class="img-1">
						</div>
						<div class="description">
							DÉVELOPPER LE COLLÈGE SAINT-JEAN BAPTISTE DE BANGOU.
						</div>
						<div class="location">
							<div class="icon">
								<%= image_tag "placeholder.svg" %>
							</div>
							<div class="location-text">
								Bangou, OUEST
							</div>
						</div>
						<div class="price-day">
							<div class="price">
								€120 (6%)
							</div>
							<div class="day">
								16 jours restants
							</div>
						</div>						
						<div class="statement">	
							<progress id="avancement" value="30" max="100"></progress>
						</div>
						<%= link_to 'Voir le projet', root_path, class:'btn-medium-yellow-w-m btn-block' %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="project-card">
						<div class="img-1">
						</div>
						<div class="description">
							DÉVELOPPER LE COLLÈGE SAINT-JEAN BAPTISTE DE BANGOU.
						</div>
						<div class="location">
							<div class="icon">
								<%= image_tag "placeholder.svg" %>
							</div>
							<div class="location-text">
								Bangou, OUEST
							</div>
						</div>
						<div class="price-day">
							<div class="price">
								€120 (6%)
							</div>
							<div class="day">
								16 jours restants
							</div>
						</div>						
						<div class="statement">	
							<progress id="avancement" value="30" max="100"></progress>
						</div>
						<%= link_to 'Voir le projet', root_path, class:'btn-medium-yellow-w-m btn-block' %>
					</div>
				</div>
			</div>
		</div>
		<div class="discover-title-project">
			Les nouveau projets
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<div class="project-card">
						<div class="img-1">
						</div>
						<div class="description">
							DÉVELOPPER LE COLLÈGE SAINT-JEAN BAPTISTE DE BANGOU.
						</div>
						<div class="location">
							<div class="icon">
								<%= image_tag "placeholder.svg" %>
							</div>
							<div class="location-text">
								Bangou, OUEST
							</div>
						</div>
						<div class="price-day">
							<div class="price">
								€120 (6%)
							</div>
							<div class="day">
								16 jours restants
							</div>
						</div>						
						<div class="statement">	
							<progress id="avancement" value="30" max="100"></progress>
						</div>
						<%= link_to 'Voir le projet', root_path, class:'btn-medium-yellow-w-m btn-block' %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="project-card">
						<div class="img-1">
						</div>
						<div class="description">
							DÉVELOPPER LE COLLÈGE SAINT-JEAN BAPTISTE DE BANGOU.
						</div>
						<div class="location">
							<div class="icon">
								<%= image_tag "placeholder.svg" %>
							</div>
							<div class="location-text">
								Bangou, OUEST
							</div>
						</div>
						<div class="price-day">
							<div class="price">
								€120 (6%)
							</div>
							<div class="day">
								16 jours restants
							</div>
						</div>						
						<div class="statement">	
							<progress id="avancement" value="30" max="100"></progress>
						</div>
						<%= link_to 'Voir le projet', root_path, class:'btn-medium-yellow-w-m btn-block' %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="project-card">
						<div class="img-1">
						</div>
						<div class="description">
							DÉVELOPPER LE COLLÈGE SAINT-JEAN BAPTISTE DE BANGOU.
						</div>
						<div class="location">
							<div class="icon">
								<%= image_tag "placeholder.svg" %>
							</div>
							<div class="location-text">
								Bangou, OUEST
							</div>
						</div>
						<div class="price-day">
							<div class="price">
								€120 (6%)
							</div>
							<div class="day">
								16 jours restants
							</div>
						</div>						
						<div class="statement">	
							<progress id="avancement" value="30" max="100"></progress>
						</div>
						<%= link_to 'Voir le projet', root_path, class:'btn-medium-yellow-w-m btn-block' %>
					</div>
				</div>
			</div>
		</div>
		<div class="see-more">
			<%= link_to 'Découvrir d\'autres projets', root_path, class: 'btn-medium-yellow-border' %>
		</div>
	</div>

	<div class="cta-project flex-container text-center">
		<div class="flex-item">
			<div class="cta-text">
				Vous êtes porteur de projet ? Lancez-vous !
			</div>
			<div class="cta-btn">
				<%= link_to 'Proposez un projet', root_path, class: 'btn-medium-white-border' %>
			</div>
		</div>
	</div>

	<div class="why text-center">
		<div class="why-text">
			POURQUOI CHOISIR FIATOPE ?
		</div>
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-lg-3">
					<div class="why-icon">
						<%= image_tag	"securite.svg" %>
					</div>
					<div class="why-title-item">
						Sécurité
					</div>
					<div class="why-description">
						Chez Fiatope, nous respectons nos engagements de confidentialité. Vos informations de paiement et vos contributions sont sécurisées.
					</div>
				</div>
				<div class="col-sm-6 col-lg-3">
					<div class="why-icon">
						<%= image_tag	"fiabilite.svg" %>
					</div>
					<div class="why-title-item">
						Fiabilité
					</div>
					<div class="why-description">
						Vous avez l'assurance que vos dons seront reçus par le porteur de projet bénéficiare. En effet la Banque de France encadre strictement l'activité de détention de fonds pour le compte de tiers et garantit la destination des fonds via l'agrément qu'elle donne à notre intermédiaire de paiement et les obligations légales de Fiatope.

						<p>Notre partenaire local se charge de remettre au porteur de projet via un processus transparent, la collecte des Fiatopers.</p>
					</div>
				</div>
				<div class="col-sm-6 col-lg-3">
					<div class="why-icon">
						<%= image_tag	"professionnalisme.svg" %>
					</div>
					<div class="why-title-item">
						Professionnalisme
					</div>
					<div class="why-description">
						Notre aptitude à sélectionner pour vous des projets ambitieux, originaux et innovants
						dans des domaines tels que l'enseignement supérieur, la santé, les technologies, l'environnement, l'agriculture, la culture. 

						<p>Nous travaillons pour cela avec de nombreux partenaires en Europe et en Afrique.</p>
					</div>
				</div>
				<div class="col-sm-6 col-lg-3">
					<div class="why-icon">
						<%= image_tag	"transparence.svg" %>
					</div>
					<div class="why-title-item">
						Transparence
					</div>
					<div class="why-description">
						Fiatope est une entreprise responsable. Nous travaillons avec des partenaires agréés par les autorités administratives et financières françaises et internationales. 

						<p>Nous mettons tout en oeuvre pour garantir la sécurité de vos informations et des fonds que vous nous confiez pour des tiers.</p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="partnership text-center">
		<div class="why-text">
			NOS PARTENAIRES
		</div>
		<div class="col-md-4">
			<div class="partner-icon">
				<%= image_tag	"oserlafrique.png" %>
			</div>
		</div>
		<div class="col-md-4">
			<div class="partner-icon">
				<%= image_tag	"oserlafrique.png" %>
			</div>
		</div>
		<div class="col-md-4">
			<div class="partner-icon">
				<%= image_tag	"oserlafrique.png" %>
			</div>
		</div>
	</div>

app/views/pages/homefitatope.html.erb
	<div class="jumbo">
		<div class="filter-black flex-container">
			<div class="flex-item text-center">
				<h1>DES SOLUTIONS POUR <br> UNE AFRIQUE EMERGEANTE.</h1>
				<%= link_to 'Découvrez les projets', root_path, class: 'btn-medium-yellow' %>
				<%= link_to 'Proposez un projet', pages_newproject_path, class: 'btn-medium-red'%>
			</div>
		</div>
	</div>

	<div class="discover text-center">
		<div class="discover-title">
			Decouvrez des projets innovants ambitieux et solides
		</div>
		<div class="discover-title-project">
			Les projets coup de coeur
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<div class="project-card">
						<div class="img-1">
						</div>
						<div class="description">
							DÉVELOPPER LE COLLÈGE SAINT-JEAN BAPTISTE DE BANGOU.
						</div>
						<div class="location">
							<div class="icon">
								<%= image_tag "placeholder.svg" %>
							</div>
							<div class="location-text">
								Bangou, OUEST
							</div>
						</div>
						<div class="price-day">
							<div class="price">
								€120 (6%)
							</div>
							<div class="day">
								16 jours restants
							</div>
						</div>						
						<div class="statement">	
							<progress id="avancement" value="30" max="100"></progress>
						</div>
						<%= link_to 'Voir le projet', root_path, class:'btn-medium-yellow-w-m btn-block' %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="project-card">
						<div class="img-1">
						</div>
						<div class="description">
							DÉVELOPPER LE COLLÈGE SAINT-JEAN BAPTISTE DE BANGOU.
						</div>
						<div class="location">
							<div class="icon">
								<%= image_tag "placeholder.svg" %>
							</div>
							<div class="location-text">
								Bangou, OUEST
							</div>
						</div>
						<div class="price-day">
							<div class="price">
								€120 (6%)
							</div>
							<div class="day">
								16 jours restants
							</div>
						</div>						
						<div class="statement">	
							<progress id="avancement" value="30" max="100"></progress>
						</div>
						<%= link_to 'Voir le projet', root_path, class:'btn-medium-yellow-w-m btn-block' %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="project-card">
						<div class="img-1">
						</div>
						<div class="description">
							DÉVELOPPER LE COLLÈGE SAINT-JEAN BAPTISTE DE BANGOU.
						</div>
						<div class="location">
							<div class="icon">
								<%= image_tag "placeholder.svg" %>
							</div>
							<div class="location-text">
								Bangou, OUEST
							</div>
						</div>
						<div class="price-day">
							<div class="price">
								€120 (6%)
							</div>
							<div class="day">
								16 jours restants
							</div>
						</div>						
						<div class="statement">	
							<progress id="avancement" value="30" max="100"></progress>
						</div>
						<%= link_to 'Voir le projet', root_path, class:'btn-medium-yellow-w-m btn-block' %>
					</div>
				</div>
			</div>
		</div>
		<div class="discover-title-project">
			Les nouveau projets
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<div class="project-card">
						<div class="img-1">
						</div>
						<div class="description">
							DÉVELOPPER LE COLLÈGE SAINT-JEAN BAPTISTE DE BANGOU.
						</div>
						<div class="location">
							<div class="icon">
								<%= image_tag "placeholder.svg" %>
							</div>
							<div class="location-text">
								Bangou, OUEST
							</div>
						</div>
						<div class="price-day">
							<div class="price">
								€120 (6%)
							</div>
							<div class="day">
								16 jours restants
							</div>
						</div>						
						<div class="statement">	
							<progress id="avancement" value="30" max="100"></progress>
						</div>
						<%= link_to 'Voir le projet', root_path, class:'btn-medium-yellow-w-m btn-block' %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="project-card">
						<div class="img-1">
						</div>
						<div class="description">
							DÉVELOPPER LE COLLÈGE SAINT-JEAN BAPTISTE DE BANGOU.
						</div>
						<div class="location">
							<div class="icon">
								<%= image_tag "placeholder.svg" %>
							</div>
							<div class="location-text">
								Bangou, OUEST
							</div>
						</div>
						<div class="price-day">
							<div class="price">
								€120 (6%)
							</div>
							<div class="day">
								16 jours restants
							</div>
						</div>						
						<div class="statement">	
							<progress id="avancement" value="30" max="100"></progress>
						</div>
						<%= link_to 'Voir le projet', root_path, class:'btn-medium-yellow-w-m btn-block' %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="project-card">
						<div class="img-1">
						</div>
						<div class="description">
							DÉVELOPPER LE COLLÈGE SAINT-JEAN BAPTISTE DE BANGOU.
						</div>
						<div class="location">
							<div class="icon">
								<%= image_tag "placeholder.svg" %>
							</div>
							<div class="location-text">
								Bangou, OUEST
							</div>
						</div>
						<div class="price-day">
							<div class="price">
								€120 (6%)
							</div>
							<div class="day">
								16 jours restants
							</div>
						</div>						
						<div class="statement">	
							<progress id="avancement" value="30" max="100"></progress>
						</div>
						<%= link_to 'Voir le projet', root_path, class:'btn-medium-yellow-w-m btn-block' %>
					</div>
				</div>
			</div>
		</div>
		<div class="see-more">
			<%= link_to 'Découvrir d\'autres projets', root_path, class: 'btn-medium-yellow-border' %>
		</div>
	</div>

	<div class="cta-project flex-container text-center">
		<div class="flex-item">
			<div class="cta-text">
				Vous êtes porteur de projet ? Lancez-vous !
			</div>
			<div class="cta-btn">
				<%= link_to 'Proposez un projet', root_path, class: 'btn-medium-white-border' %>
			</div>
		</div>
	</div>

	<div class="why text-center">
		<div class="why-text">
			POURQUOI CHOISIR FIATOPE ?
		</div>
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-lg-3">
					<div class="why-icon">
						<%= image_tag	"securite.svg" %>
					</div>
					<div class="why-title-item">
						Sécurité
					</div>
					<div class="why-description">
						Chez Fiatope, nous respectons nos engagements de confidentialité. Vos informations de paiement et vos contributions sont sécurisées.
					</div>
				</div>
				<div class="col-sm-6 col-lg-3">
					<div class="why-icon">
						<%= image_tag	"fiabilite.svg" %>
					</div>
					<div class="why-title-item">
						Fiabilité
					</div>
					<div class="why-description">
						Vous avez l'assurance que vos dons seront reçus par le porteur de projet bénéficiare. En effet la Banque de France encadre strictement l'activité de détention de fonds pour le compte de tiers et garantit la destination des fonds via l'agrément qu'elle donne à notre intermédiaire de paiement et les obligations légales de Fiatope.

						<p>Notre partenaire local se charge de remettre au porteur de projet via un processus transparent, la collecte des Fiatopers.</p>
					</div>
				</div>
				<div class="col-sm-6 col-lg-3">
					<div class="why-icon">
						<%= image_tag	"professionnalisme.svg" %>
					</div>
					<div class="why-title-item">
						Professionnalisme
					</div>
					<div class="why-description">
						Notre aptitude à sélectionner pour vous des projets ambitieux, originaux et innovants
						dans des domaines tels que l'enseignement supérieur, la santé, les technologies, l'environnement, l'agriculture, la culture. 

						<p>Nous travaillons pour cela avec de nombreux partenaires en Europe et en Afrique.</p>
					</div>
				</div>
				<div class="col-sm-6 col-lg-3">
					<div class="why-icon">
						<%= image_tag	"transparence.svg" %>
					</div>
					<div class="why-title-item">
						Transparence
					</div>
					<div class="why-description">
						Fiatope est une entreprise responsable. Nous travaillons avec des partenaires agréés par les autorités administratives et financières françaises et internationales. 

						<p>Nous mettons tout en oeuvre pour garantir la sécurité de vos informations et des fonds que vous nous confiez pour des tiers.</p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="partnership text-center">
		<div class="why-text">
			NOS PARTENAIRES
		</div>
		<div class="col-md-3">
			<div class="partner-icon">
				<%= image_tag	"oserlafrique.png" %>
			</div>
		</div>
		<div class="col-md-3">
			<div class="partner-icon">
				<%= image_tag	"cofides.jpg" %>
			</div>
		</div>
		<div class="col-md-3">
			<div class="partner-icon">
				<%= image_tag	"ASI.jpg" %>
			</div>
		</div>
		<div class="col-md-3">
			<div class="partner-icon">
				<%= image_tag	"siad.jpg" %>
			</div>
		</div>
	</div>

app/views/pages/kwendoo.html.erb
kwendoo.html.erb

app/views/pages/newproject.html.erb
<div class="background-pano">
	<div class="background-pano-title">
		<h2> Mon projet </h2>
	</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_fiatope.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
    	<%= link_to t(".top_call_to_action", default: "Découvrir les projets"), "#", class: "navbar-wagon-item navbar-wagon-link" %>

    	<%= link_to t(".top_call_to_action", default: "Comment ça marche ?"), "#", class: "navbar-wagon-item navbar-wagon-link" %>

    	<%= link_to t(".top_call_to_action", default: "Blog"), "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Proposez un projet"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbarfiatope.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_fiatope.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
    	<%= link_to t(".top_call_to_action", default: "Découvrir les projets"), "#", class: "navbar-wagon-item navbar-wagon-link" %>

    	<%= link_to t(".top_call_to_action", default: "Comment ça marche ?"), "#", class: "navbar-wagon-item navbar-wagon-link" %>

    	<%= link_to t(".top_call_to_action", default: "Blog"), "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Proposez un projet"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>